---
- name: Initialize master node
  command: "kubeadm init --token-ttl=0 --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr 10.244.0.0/16"
  become: yes
  register: kube_init
  tags:
    - kube
    - kube_init

- debug:
    var: kube_init
  tags:
    - kube
    - kube_init

- set_fact:
    kube_master_token: "{{ kube_init.stdout | regex_search(token_regexp) }}"
    kube_join_cli: "{{ kube_init.stdout | regex_search(join_regexp) }}"
  vars:
    token_regexp: "(?<=\\[bootstraptoken\\] using token: )[a-z0-9]{6}\\.[a-z0-9]{16}"
    join_regexp: "kubeadm join .+"
  tags:
    - kube
    - kube_init

- debug:
    var: kube_master_token
  tags:
    - kube
    - kube_init

- debug:
    var: kube_join_cli
  tags:
    - kube
    - kube_init

- file:
    path: "~/.kube"
    state: directory
  tags:
    - kube
    - kube_init

- copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "~{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: pi
  become: yes
  tags:
    - kube
    - kube_init

- name: Restart k8s service
  systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted
  become: yes
    - kube
    - kube_init


#- name: Install Weave Net overlay network driver
#  shell: "kubectl apply -f \"https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')\""
#  tags:
#    - kube
#    - kube_net

- name: Install flannel
  shell: "curl -sSL https://rawgit.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml | sed \"s/amd64/arm/g\" | kubectl create -f -"
  tags:
    - kube
    - kube_net

- name: Check Helm installation
  stat:
    path: /usr/local/bin/helm
  register: has_helm
  tags:
    - helm

- name: Download Helm installer
  unarchive:
    src: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-arm.tar.gz"
    dest: /tmp
    remote_src: yes
  become: yes
  when: has_helm.stat.exists == False
  tags:
    - helm

- name: Install Helm
  command: "mv /tmp/linux-arm/{{ item }} /usr/local/bin/{{ item }}"
  become: yes
  when: has_helm.stat.exists == False
  loop:
    - "helm"
    - "tiller"
  tags:
    - helm

- copy:
    src: "{{ role_path }}/files/tiller-rbac.yml"
    dest: /tmp/k8s-master/
  tags:
    - helm

- name: Configure tiller service account
  command: 'kubectl apply -f /tmp/k8s-master/tiller-rbac.yml'
  tags:
    - helm

- name: Install Tiller
  command: /usr/local/bin/helm init --upgrade --tiller-image=jessestuart/tiller:v2.9.1 --service-account tiller
# TODO améliorer
  when: has_helm.stat.exists == False
  tags:
    - helm
    #mkdir -p $HOME/.kube
#  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#  sudo chown $(id -u):$(id -g) $HOME/.kube/config


