---
- name: Initialize master node
  command: "kubeadm init --token-ttl=0 --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr 10.244.0.0/16"
  become: yes
  register: kube_init
  tags:
    - kube
    - kube_init

- debug:
    var: kube_init
  tags:
    - kube
    - kube_init

- set_fact:
    kube_master_token: "{{ kube_init.stdout | regex_search(token_regexp) }}"
    kube_join_cli: "{{ kube_init.stdout | regex_search(join_regexp) }}"
  vars:
    token_regexp: "(?<=\\[bootstraptoken\\] using token: )[a-z0-9]{6}\\.[a-z0-9]{16}"
    join_regexp: "kubeadm join .+"
  tags:
    - kube
    - kube_init

- debug:
    var: kube_master_token
  tags:
    - kube
    - kube_init

- debug:
    var: kube_join_cli
  tags:
    - kube
    - kube_init

- file:
    path: "~/.kube"
    state: directory
  tags:
    - kube
    - kube_init

- copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "~{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: pi
  become: yes
  tags:
    - kube
    - kube_init

- name: Restart k8s service
  systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted
  become: yes
    - kube
    - kube_init


#- name: Install Weave Net overlay network driver
#  shell: "kubectl apply -f \"https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')\""
#  tags:
#    - kube
#    - kube_net

- name: Install flannel
  shell: "curl -sSL https://rawgit.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml | sed \"s/amd64/arm/g\" | kubectl create -f -"
  tags:
    - kube
    - kube_net


#mkdir -p $HOME/.kube
#  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#  sudo chown $(id -u):$(id -g) $HOME/.kube/config
