---
- name: Set hostname
  command: "raspi-config nonint do_hostname {{ inventory_hostname }}"

- name: Configure static ip & network
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: 0664

- name: Get Docker installer
  get_url:
    url: http://get.docker.com
    dest: /tmp/install-docker
    mode: "u+x"

- name: Install Docker
  command: /tmp/install-docker

- name: Remove installer
  file:
    path: /tmp/install-docker
    state: absent

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    state: present
    groups: docker

- name: Turn off swap
  command: dphys-swapfile swapoff

- name: Remove swap
  command: dphys-swapfile uninstall

- name: Remove swap utility
  command: update-rc.d dphys-swapfile remove
