---
- name: Set hostname
  command: "raspi-config nonint do_hostname {{ inventory_hostname }}"

- name: Configure static ip & network
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: 0664

- name: Get Docker installer
  get_url:
    url: http://get.docker.com
    dest: /tmp/install-docker
    mode: "u+x"

- name: Install Docker
  command: /tmp/install-docker

- name: Remove installer
  file:
    path: /tmp/install-docker
    state: absent

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    state: present
    groups: docker

- name: Turn off swap
  command: dphys-swapfile swapoff

- name: Remove swap
  command: dphys-swapfile uninstall

- name: Remove swap utility
  command: update-rc.d dphys-swapfile remove

- name: Configure cgroups
  lineinfile:
    path: /boot/cmdline.txt
    line: group_enable=cpuset cgroup_memory=1
    state: present
  register: cgroups_result

- name: Reboot on cgroup config change
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: cgroups_result is changed

- name: Wait for the reboot to complete if there was a change
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: cgroups_result is changed

- name: Add k8s repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add k8s repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    update_cache: yes
    state: present

- name: Install kubeadm
  apt:
    name: kubeadm
    state: latest
