---
- name: Create ssh folder
  file:
    path: "~/.ssh"
    state: directory
    mode: 0700
  tags:
    - ssh

- name: Set authorized ssh keys
  template:
    src: authorized_keys.j2
    dest: "~/.ssh/authorized_keys"
    mode: 0600
  tags:
    - ssh

- name: Set hostname
  command: "raspi-config nonint do_hostname {{ inventory_hostname }}"
  become: yes
  register: hostname
  tags:
    - hostname

- debug:
    var: hostname
  tags:
    - hostname

- name: Configure static ip & network
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: 0664
  register: dhcpcd
  tags:
    - static_ip

- name: Restart dhcpcd
  systemd:
    daemon_reload: yes
    name: dhcpcd
    state: restarted
  when: dhcpcd is changed
  tags:
    - static_ip

- name: Configure cgroups
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    mode: 0755
  register: cmdline
  tags:
    - cgroups

- debug:
    var: cmdline
  tags:
    - cgroups

- name: Upgrade all packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
    autoclean: yes
  become: yes

- name: Reboot
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  become: yes
  when: cmdline or hostname is changed
  tags:
    - cgroups
    - hostname

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: cmdline or hostname is changed
  tags:
    - cgroups
    - hostname

- name: Turn off & remove swap
  shell: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove
  become: yes
  tags:
    - docker
    - swap

- name: Check docker installation
  stat:
    path: /usr/bin/docker
  register: has_docker

- name: Get Docker installer
  get_url:
    url: http://get.docker.com
    dest: /tmp/install-docker
    mode: "u+x"
  when: has_docker.stat.exists == False
  tags:
    - docker

- name: Install Docker
  command: /tmp/install-docker
  become: yes
  when: has_docker.stat.exists == False
  tags:
    - docker

- name: Remove installer
  file:
    path: /tmp/install-docker
    state: absent
  tags:
    - docker

- name: Create Docker group
  group:
    name: docker
    state: present
  become: yes
  tags:
    - docker

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    state: present
    groups: docker
  tags:
    - docker

- name: Add k8s repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: yes
  tags:
    - kube

- name: Add k8s repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    update_cache: yes
    state: present
  become: yes
  tags:
    - kube

- name: Install kubeadm
  apt:
    name: kubeadm
    state: latest
    autoclean: yes
    autoremove: yes
  become: yes
  tags:
    - kube
