---
- name: Create ssh folder
  file:
    path: "~{{ ansible_user }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: pi
    mode: 0700

- name: Set authorized ssh keys
  template:
    src: authorized_keys.j2
    dest: "~{{ ansible_user }}/.ssh/authorized_keys"
    owner: "{{ ansible_user }}"
    group: pi
    mode: 0600

- name: Set hostname
  command: "raspi-config nonint do_hostname {{ inventory_hostname }}"
  register: hostname

- name: Configure static ip & network
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: 0664
  register: dhcpcd

- name: Restart dhcpcd
  systemd:
    daemon_reload: yes
    name: dhcpcd
    state: restarted
  when: dhcpcd is changed

- name: Turn off swap
  command: dphys-swapfile swapoff

- name: Remove swap
  command: dphys-swapfile uninstall

- name: Remove swap utility
  command: update-rc.d dphys-swapfile remove

- name: Configure cgroups
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    mode: 0755
  register: cmdline

- name: Reboot on cgroup config change
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: cmdline is changed

- name: Wait for the reboot to complete if there was a change
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: cmdline or hostname is changed

- name: Get Docker installer
  get_url:
    url: http://get.docker.com
    dest: /tmp/install-docker
    mode: "u+x"

- name: Install Docker
  command: /tmp/install-docker

- name: Remove installer
  file:
    path: /tmp/install-docker
    state: absent

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    state: present
    groups: docker

- name: Add k8s repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add k8s repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-stretch main
    update_cache: yes
    state: present

- name: Install kubeadm
  apt:
    name: kubeadm
    state: latest
